apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mysql
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3306
    nodePort: {{ .Values.service.nodePort }}
