replicaCount: 1

image:
  repository: mysql
  tag: "5.7"
  pullPolicy: IfNotPresent

# Environment variables for MySQL
mysqlRootPassword: gr8pass

service:
  type: NodePort
  port: 3306
  nodePort: 30306

persistence:
  enabled: true
  existingClaim: mysql-pvc
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}
